version: '3.9'

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data


  app:
    build:
      context: ..
      dockerfile: Docker/images/project.Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
      
volumes:
  postgres_data:
